<?php

/**
 * @file
 * Contains Debug module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function helfi_debug_theme() {
  return [
    'debug_item' => [
      'variables' => [
        'id' => NULL,
        'label' => NULL,
        'data' => [],
      ],
      'template' => 'debug-item',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function helfi_debug_theme_suggestions_debug_item(array $variables) {
  $suggestions = [];
  $suggestions[] = 'debug_item__' . strtr($variables['id'], '.', '_');
  return $suggestions;
}
